name: 🐞 Report Bug
description: File a bug
title: "[Bug]"
type: "bug"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file out this bug report 🙌
  - type: dropdown
    id: project
    attributes:
      label: Where did you encounter this bug?
      multiple: true
      options:
        - Instill Core
        - SDK
        - CLI
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug and steps to reproduce
      description: A concise description of what you're experiencing.
      placeholder: |
        ## Description
        A concise description of what you're experiencing.

        ## Steps to Reproduce
        1. Go to ...
        2. Click on ...
        3. ...

        Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Result
      description: What's happening right now that is different from what is expected.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Technical Details
      description: |
        examples:
          - **Instill Core version**: 0.13.0-alpha
          - **OS**: Linux
          - **Browser**: Chrome
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
