name: ✨ Request Feature
description: Request for a new feature
title: "[Feature]"
type: "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file out this feature request 🙌
  - type: dropdown
    id: project
    attributes:
      label: Where do you intend to apply this feature?
      multiple: true
      options:
        - Instill Core
        - SDK
        - CLI
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Problem and Proposed Solution
      description: Outline how you envision the feature functioning and its potential impact.
      placeholder: |
        ## Problem
        Provide a clear and concise description of what the problem is. For example, "I'm always frustrated when..."

        ## Proposed Feature
        A concise description of the feature you're proposing and its potential impact.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Is there anything else you can add about the proposal?
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
