name: ✨ Feature Request
description: Suggest a feature
title: "[Feature] <title>"
labels: ["✨ feature", "need-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file out this feature request 🙌
  - type: checkboxes
    attributes:
      label: Is There an Existing Issue for This?
      description: Please search to see if an issue already exists for the feature you requested.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What Instill project are you seeking to apply this feature to?
      multiple: false
      options:
        - Instill Protocol
        - Instill Core
        - Instill VDP
        - Instill Model
        - Instill Console
        - Instill CLI
        - Instill SDK
        - Instill Website
        - I am not sure
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your Proposal Related to a Problem?
      description: Provide a clear and concise description of what the problem is. For example, "I'm always frustrated when..."
      placeholder: Write your answer here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe Your Proposed Solution
      description: Outline how you envision the feature functioning and its potential impact and let us know about other solutions you've tried or researched.
      placeholder: Write your answer here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Highlight the Benefits
      description: Highlight the advantages of implementing this feature.
      placeholder: Write your answer here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Is there anything else you can add about the proposal?
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
