name: Add Label to PR

on:
  workflow_call:
    secrets:
      botGitHubToken:
        description: "A personal access token token (classic) with repo scopes"
        required: true

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.botGitHubToken }}
